In [45]:
import numpy as np
import matplotlib.pyplot as plt
import os, time
from skimage import io
from skimage.feature import hog
from sklearn import svm
from sklearn import linear_model
from sklearn import metrics
from sklearn import calibration
import pickle
import copy
import csv

In [46]:
plt.rcParams['figure.figsize'] = (15,15)
plt.rcParams.update({'font.size': 12})

In [47]:
RESULTS_FH = None # global

In [48]:
DIR = 'Individual_Component'
SEED = 42

# [HOG parameters]
# img (w,h): (64,80)
# NFEATURES = nblocks * norientations/cell * ncells/block
POWER_LAW_COMPRESSION = True

# BLOCK_SIZE_LIST = [1, 2, 3, 4]
# BLOCK_NORM_LIST = ['L2-Hys'] # available: ['L1', 'L1-sqrt', 'L2', 'L2-Hys']
# CELL_PIXEL_LIST = [4, 5, 6, 7, 8, 9, 10, 14]
# ORIENTATION_LIST = [6, 7, 8, 9, 10, 11, 12]
# NPOS_TRAINING_IMGS = 3000
# NNEG_TRAINING_IMGS = 3000

## (Test platform test runs)

# BLOCK_SIZE_LIST = [1]
# BLOCK_NORM_LIST = ['L1']
# CELL_PIXEL_LIST = [4]
# ORIENTATION_LIST = [8, 6]
# NPOS_TRAINING_IMGS = 10
# NNEG_TRAINING_IMGS = 10

BLOCK_SIZE_LIST = [1,2,4]
BLOCK_NORM_LIST = ['L2-Hys'] # available: ['L1', 'L1-sqrt', 'L2', 'L2-Hys']
CELL_PIXEL_LIST = [5, 6, 7, 8, 9, 10, 14]
ORIENTATION_LIST = [7,11]
NPOS_TRAINING_IMGS = 3000
NNEG_TRAINING_IMGS = 3000

In [49]:
if RESULTS_FH != None:
    RESULTS_FH.close()
print('Results file closed.')

Results file closed.


In [50]:
def list_mul(l, num):
    return tuple(map(lambda x: int(num * x), l))

# Histogram of Oriented Gradients
def run_hog(img, visualize=False):
    global NORIENTATIONS, CELL_PIXELSHAPE, CELLS_PER_BLOCK, BLOCK_NORM, POWER_LAW_COMPRESSION
    result = hog(img, orientations=NORIENTATIONS, 
                 pixels_per_cell=CELL_PIXELSHAPE, cells_per_block=CELLS_PER_BLOCK, 
                 block_norm=BLOCK_NORM, visualize=visualize, transform_sqrt=POWER_LAW_COMPRESSION,
                 multichannel=True)
    return result

In [51]:
# Reference: https://www.kaggle.com/manikg/training-svm-classifier-with-hog-features

def log_result(s, on_console=True): # debug log...
    global RESULTS_FH
    if on_console:
        print(s)
    print(s, file=RESULTS_FH)

# Code to load the dataset
def get_dataset_fp(is_train):
    if is_train:
        subroot = 'train'
    else:
        subroot = 'test'
    base_fp = os.path.join(DIR, subroot)
    pos_dirs = []
    neg_dirs = []
    for dir_name in os.listdir(base_fp): # all files & dirs
        subfp = os.path.join(base_fp, dir_name)
        if not os.path.isdir(subfp):
            continue    
        for subdir_name in os.listdir(subfp):
            subsubfp = os.path.join(subfp, subdir_name)
            if not os.path.isdir(subsubfp):
                continue
            if 'positive' in dir_name:
                pos_dirs.append(subsubfp)
            elif 'negative' in dir_name:
                neg_dirs.append(subsubfp)
    return pos_dirs, neg_dirs

def get_subset_images(fp, nimgs=None, preproc=False):
    results = []
    results_fp = []
    count = 0
    for img_fn in os.listdir(fp):
        img_fp = os.path.join(fp, img_fn)
        if os.path.isdir(img_fp) or img_fn[-4:].lower() != '.pnm':
            continue
        img = io.imread(img_fp)
        if preproc: # proprocess as HOG
            hog_fd = run_hog(img)
            results.append(hog_fd)
        else:
            results.append(img)
        results_fp.append(img_fp)
        count += 1 # restrict num imgs loaded
        if nimgs != None and count >= nimgs:
            break
    return results, results_fp

NO_PERSON = 0
IS_PERSON = 1

#def load_images(is_train, shuffle, npos_imgs=None, nneg_imgs=None, save_fn=None):
def load_images(is_train, npos_imgs=None, nneg_imgs=None):
    pos_dirs, neg_dirs = get_dataset_fp(is_train=is_train)    
    x_train = []
    y_train = []
    fp_train = []
    # get preprocessed training/testing data
    for fp in pos_dirs:
        start_time = time.time()
        cur_subset, cur_subset_fp = get_subset_images(fp, npos_imgs, False)
        x_train += cur_subset
        fp_train += cur_subset_fp
        log_result('  * {:.3f}s runtime (images loaded): {}'.format(time.time() - start_time,fp))
        if npos_imgs != None:
            npos_imgs -= len(cur_subset)
            if npos_imgs <= 0:
                break
    pos_length = len(x_train)
    y_train += [IS_PERSON] * pos_length
    
    for fp in neg_dirs:
        start_time = time.time()
        cur_subset, cur_subset_fp = get_subset_images(fp, nneg_imgs, False)
        x_train += cur_subset
        fp_train += cur_subset_fp
        log_result('  * {:.3f}s runtime (images loaded): {}'.format(time.time() - start_time,fp))
        if nneg_imgs != None:
            nneg_imgs -= len(cur_subset)
            if nneg_imgs <= 0:
                break
    y_train += [NO_PERSON] * (len(x_train) - pos_length)
    return x_train, y_train, fp_train

def images_to_hog(x_train, y_train, fp_train, shuffle, save_fn=None):
    # convert each img to hog (intermed step added to cache original unproc'd images)
    start_time = time.time()
    for i in range(len(x_train)):
        x_train[i] = run_hog(x_train[i])
    hog_shape = x_train[0].shape
    log_result('  * {:.3f}s runtime (conversion to HOG)'.format(time.time() - start_time))
    
    # shuffle training data
    #print('Reformatting data...')
    x_train = np.array(x_train)
    y_train = np.array(y_train)
    fp_train_index = np.arange(len(fp_train)) # create unique IDs (from 0)
    
    if shuffle:
        y_train = y_train.reshape(len(y_train),1)
        fp_train_index = fp_train_index.reshape(len(fp_train_index),1)
        
        data_frame = np.hstack((x_train,y_train, fp_train_index))
        #print('Reshuffling data...')
        start_time = time.time()
        np.random.seed(SEED)
        np.random.shuffle(data_frame)
        x_train = data_frame[:,:-2]
        y_train = data_frame[:,-2].ravel()
        fp_train_index = data_frame[:,-1].ravel()
        log_result('  * {:.3f}s runtime (shuffling)'.format(time.time() - start_time))
    
    log_result('HOG descriptor size: ' + str(hog_shape))
    result = (x_train, y_train, fp_train_index, fp_train)
    # save loaded images
    if save_fn != None:
        with open(save_fn, 'wb') as fh:
            pickle.dump(result, fh)
    return result
    
# Code to generate the SVM model
def gen_model(model_fn, x_train, y_train):
    # generate SVM model
    start_time = time.time()
    #clf = svm.SVC(probability=True)
    #clf = linear_model.SGDClassifier()
    clf = calibration.CalibratedClassifierCV(base_estimator = svm.LinearSVC(loss='hinge'), cv=5)
    clf.fit(x_train, y_train)
    log_result('{:.3f}s runtime (SGD training)'.format(time.time() - start_time))
    
    # save SVM model
    with open(model_fn, 'wb') as fh:
        pickle.dump(clf, fh)
    return clf

In [52]:
# Computes statistics for the classifier's performance
def run_test(clf, x_test, y_test):
    start_time = time.time()
    y_pred = clf.predict(x_test)
    y_prob = clf.predict_proba(x_test)
        
    # y_prob: https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
    #  - shape: (nsamples, nclasses), by order of `clf.classes_`
    elapsed_time = time.time() - start_time
    auc = metrics.roc_auc_score(y_test, y_prob[:,IS_PERSON], average='weighted')
    accuracy = metrics.accuracy_score(y_test, y_pred)
    precision = metrics.precision_score(y_test, y_pred, average='weighted')
    recall = metrics.recall_score(y_test, y_pred, average='weighted')
    confusion_matrix = metrics.confusion_matrix(y_test, y_pred)
    stats = {'Prediction Time':elapsed_time, 'AUC':auc, 'Accuracy':accuracy, 'Precision':precision, 
             'Recall':recall, 'Confusion Matrix':confusion_matrix}
    
    log_result('  * {:.6f}s prediction time ({:.6f} s/image)'.format(elapsed_time, elapsed_time/len(y_test)))
    log_result('  * AUC (weighted): {:.9f}'.format(auc))
    log_result('  * Accuracy: {:.9f}'.format(accuracy))
    log_result('  * Precision (weighted): {:.9f}'.format(precision))
    log_result('  * Recall (weighted): {:.9f}'.format(recall))
    log_result('  * Confusion Matrix:')
    log_result(str(confusion_matrix))
    return y_pred, y_prob, stats

# Returns all image file paths detected falsely
def filter_failed_fp(y_pred, y_test, fp_test_index, fp_test):
    failed_fp = []
    for i in range(len(y_pred)):
        if y_pred[i] != y_test[i]:
            if y_pred[i] == NO_PERSON:
                label = 'FN'
            else:
                label = 'FP'
            failed_fp.append( (label, fp_test[int(fp_test_index[i])]) )
    return failed_fp

In [53]:
# 1. Generate SVM model (and training images) or load cached result
def get_svm_model(cur_dir_contents, SVM_MODEL, PRE_TRAINING_IMGS):
    global NPOS_TRAINING_IMGS,NNEG_TRAINING_IMGS
    global CACHED_UNPROC_TRAINING # training
    if SVM_MODEL not in cur_dir_contents:
        log_result('\n[Training SVM model]:')
        # get unprocessed images
        if CACHED_UNPROC_TRAINING == None: 
            x_train, y_train, fp_train = load_images(True, NPOS_TRAINING_IMGS,NNEG_TRAINING_IMGS)
            CACHED_UNPROC_TRAINING = (copy.deepcopy(x_train), copy.deepcopy(y_train), copy.deepcopy(fp_train))
        else:
            log_result('  * Loading cached unprocessed images from RAM')
            start_time = time.time()
            x_train, y_train, fp_train = copy.deepcopy(CACHED_UNPROC_TRAINING)
            log_result('    {:.3f}s loading time'.format(time.time() - start_time))
        # process images, generate model
        x_train, y_train, fp_train_index, fp_train = images_to_hog(x_train, y_train, fp_train, True, save_fn=PRE_TRAINING_IMGS)
        clf = gen_model(SVM_MODEL,x_train,y_train)
    else:
        log_result('\n[Loading cached SVM model & training images]:')
        with open(SVM_MODEL, 'rb') as fh:
            clf = pickle.load(fh)
        with open(PRE_TRAINING_IMGS, 'rb') as fh:
            x_train, y_train, fp_train_index, fp_train = pickle.load(fh)
            
    log_result('Number of training images loaded: {}'.format(len(x_train)))
    return x_train, y_train, fp_train_index, fp_train, clf

# 2. Generate test images or load cached result
def get_test_imgs(cur_dir_contents, PRE_TESTING_IMGS):
    global CACHED_UNPROC_TESTING  # testing
    # Generate test images or load cached result
    if PRE_TESTING_IMGS not in cur_dir_contents:
        log_result('\n[Generating test images]:')
        # get unprocessed images
        if CACHED_UNPROC_TESTING == None:
            x_test, y_test, fp_test = load_images(False)
            CACHED_UNPROC_TESTING = (copy.deepcopy(x_test), copy.deepcopy(y_test), copy.deepcopy(fp_test))
        else:
            log_result('  * Loading cached unprocessed test images from RAM')
            start_time = time.time()
            x_test, y_test, fp_test = copy.deepcopy(CACHED_UNPROC_TESTING)
            log_result('    {:.3f}s loading time'.format(time.time() - start_time))
        # process images, generate model
        x_test, y_test, fp_test_index, fp_test = images_to_hog(x_test, y_test, fp_test, True, save_fn=PRE_TESTING_IMGS)
    else:
        log_result('\n[Loading cached test images]:')
        with open(PRE_TESTING_IMGS, 'rb') as fh:
            x_test, y_test, fp_test_index, fp_test = pickle.load(fh)
    
    log_result('Number of testing images loaded: {}'.format(len(x_test)))
    return x_test, y_test, fp_test_index, fp_test
            
# 3. Evaluate performance (for all permutations)
#    call: run_test()
#    manual post-analysis: filter_failed_fp()

# Wrapper for single iteration. Note: all CSV write logic to be contained here. (hack)
def run_hogsvm():
    global NORIENTATIONS, CELL_PIXELSHAPE, CELLS_PER_BLOCK, BLOCK_NORM, POWER_LAW_COMPRESSION
    global RESULTS_FH, CSV_LINE
    base_fn = '_ori({})_cellpix({})_blksze({})_blknrm({})'.format(
        NORIENTATIONS, CELL_PIXELSHAPE[0], CELLS_PER_BLOCK[0], BLOCK_NORM)
    pickle_type = '.pickle'
    text_type = '.txt'
    SVM_MODEL = 'hogsvm_model' + base_fn + pickle_type
    PRE_TRAINING_IMGS = 'hogsvm_train' + base_fn + pickle_type
    PRE_TESTING_IMGS = 'hogsvm_test' + base_fn + pickle_type
    results_fn = 'hogsvm_result' + base_fn + text_type
    
    cur_dir_contents = os.listdir('.')
    RESULTS_FH = open(results_fn, 'w')
    log_result('[Current parameter sweep]:')
    log_result('  * Number of orientations: {}'.format(NORIENTATIONS))
    log_result('  * Cell pixel shape: {}'.format(CELL_PIXELSHAPE))
    log_result('  * Number of cells per block: {}'.format(CELLS_PER_BLOCK))
    log_result('  * Block normalisation method: {}'.format(BLOCK_NORM))
    log_result('  * Power law compression (preprocessing) on: {}'.format(POWER_LAW_COMPRESSION))
    # (NOTE: actually, power law is square root --> slightly different method)
    
    # load svm model and test dataset
    x_train, y_train, fp_train_index, fp_train, clf = get_svm_model(cur_dir_contents, SVM_MODEL, PRE_TRAINING_IMGS)
    x_test, y_test, fp_test_index, fp_test          = get_test_imgs(cur_dir_contents, PRE_TESTING_IMGS)
    # * (CSV): get hog shape (duplicated logic)
    CSV_LINE.append(x_train.shape[1]) # 'Feature Size'
    
    # evaluate on test and training datasets (as a crude check for overfitting)
    log_result('\n[Classifier statistics (on test data)]:')
    y_pred, y_prob, stats_test = run_test(clf, x_test, y_test)
    log_result('\n[Classifier statistics (on training data)]:')
    y_pred_training, y_prob_training, stats_train = run_test(clf, x_train, y_train)
    # * (CSV): add stats
    CSV_LINE += [stats_test['AUC'], stats_test['Accuracy'], stats_test['Precision'], 
                 stats_test['Recall'], stats_train['Accuracy'], stats_test['Prediction Time']]
    tn_teststat, fp_teststat, fn_teststat, tp_teststat = stats_test['Confusion Matrix'].ravel()
    CSV_LINE += [tp_teststat, tn_teststat, fp_teststat, fn_teststat]
    
    # identify all false results
    failed_fp = filter_failed_fp(y_pred, y_test, fp_test_index, fp_test)
    log_result('\n[Falsely detected images]:')
    for label, fp in failed_fp:
        log_result('  * {}: {}'.format(label,fp), on_console=False)

    RESULTS_FH.close()
    RESULTS_FH = None

In [54]:
# [PARAMETER SWEEP]
ntests = len(BLOCK_SIZE_LIST) * len(BLOCK_NORM_LIST) * len(CELL_PIXEL_LIST) * len(ORIENTATION_LIST)
count = 1
test_start_time = time.time()

CACHED_UNPROC_TRAINING = None
CACHED_UNPROC_TESTING = None
CSV_LINE = None

csv_fh = open('hogsvm_result_all.csv', 'w', newline='')
csv_writer = csv.writer(csv_fh)

csv_headers = ['Test', 'Cells per Block', 'Pixels per Cell', 'Orientations', 
               'Feature Size', 'AUC', 'Accuracy', 'Precision', 'Recall', 
               'Training Accuracy', 'Prediction Time (s)',
               'TP', 'TN', 'FP', 'FN'] # must write to in same order
csv_writer.writerow(csv_headers)

# block parameters
for block_size in BLOCK_SIZE_LIST:
    CELLS_PER_BLOCK = (block_size, block_size)
    for BLOCK_NORM in BLOCK_NORM_LIST:
        # cell/orientation parameters
        for cp in CELL_PIXEL_LIST:
            CELL_PIXELSHAPE = (cp,cp)
            for NORIENTATIONS in ORIENTATION_LIST:
                print('\n####[TEST {}/{}]##################################################################'.format(count,ntests))
                CSV_LINE = [count, block_size, cp, NORIENTATIONS]
                run_hogsvm()
                csv_writer.writerow(CSV_LINE)
                count += 1
# close file
csv_fh.close()


####[TEST 1/42]##################################################################
[Current parameter sweep]:
  * Number of orientations: 7
  * Cell pixel shape: (5, 5)
  * Number of cells per block: (1, 1)
  * Block normalisation method: L2-Hys
  * Power law compression (preprocessing) on: True

[Training SVM model]:
  * 0.635s runtime (images loaded): Individual_Component\train\train_positive_A\00000000
  * 0.602s runtime (images loaded): Individual_Component\train\train_positive_A\00000001
  * 0.625s runtime (images loaded): Individual_Component\train\train_positive_A\00000002
  * 0.614s runtime (images loaded): Individual_Component\train\train_negative_A\00000000
  * 0.589s runtime (images loaded): Individual_Component\train\train_negative_A\00000001
  * 0.713s runtime (images loaded): Individual_Component\train\train_negative_A\00000002
  * 29.962s runtime (conversion to HOG)
  * 0.028s runtime (shuffling)
HOG descriptor size: (1344,)
5.362s runtime (SGD training)
Number of traini

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", 

5.208s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.079s loading time
  * 38.940s runtime (conversion to HOG)
  * 0.034s runtime (shuffling)
HOG descriptor size: (910,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 0.639244s prediction time (0.000068 s/image)
  * AUC (weighted): 0.995013403
  * Accuracy: 0.968171725
  * Precision (weighted): 0.968373258
  * Recall (weighted): 0.968171725
  * Confusion Matrix:
[[5819  181]
 [ 120 3337]]

[Classifier statistics (on training data)]:
  * 0.651258s prediction time (0.000109 s/image)
  * AUC (weighted): 1.000000000
  * Accuracy: 1.000000000
  * Precision (weighted): 1.000000000
  * Recall (weighted): 1.000000000
  * Confusion Matrix:
[[3000    0]
 [   0 3000]]

[Falsely detected images]:

####[TEST 4/42]##################################################################
[Current parameter sweep]:
  * Numbe

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", 

3.772s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.070s loading time
  * 28.498s runtime (conversion to HOG)
  * 0.027s runtime (shuffling)
HOG descriptor size: (693,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 0.423037s prediction time (0.000045 s/image)
  * AUC (weighted): 0.992528830
  * Accuracy: 0.959500899
  * Precision (weighted): 0.960071692
  * Recall (weighted): 0.959500899
  * Confusion Matrix:
[[5751  249]
 [ 134 3323]]

[Classifier statistics (on training data)]:
  * 0.288349s prediction time (0.000048 s/image)
  * AUC (weighted): 0.999680222
  * Accuracy: 0.998333333
  * Precision (weighted): 0.998336877
  * Recall (weighted): 0.998333333
  * Confusion Matrix:
[[2991    9]
 [   1 2999]]

[Falsely detected images]:

####[TEST 6/42]##################################################################
[Current parameter sweep]:
  * Numbe

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", 

3.185s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.094s loading time
  * 30.628s runtime (conversion to HOG)
  * 0.040s runtime (shuffling)
HOG descriptor size: (560,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 0.473101s prediction time (0.000050 s/image)
  * AUC (weighted): 0.993332899
  * Accuracy: 0.966374114
  * Precision (weighted): 0.966725964
  * Recall (weighted): 0.966374114
  * Confusion Matrix:
[[5797  203]
 [ 115 3342]]

[Classifier statistics (on training data)]:
  * 0.271276s prediction time (0.000045 s/image)
  * AUC (weighted): 0.998766222
  * Accuracy: 0.990333333
  * Precision (weighted): 0.990336820
  * Recall (weighted): 0.990333333
  * Confusion Matrix:
[[2975   25]
 [  33 2967]]

[Falsely detected images]:

####[TEST 8/42]##################################################################
[Current parameter sweep]:
  * Numbe

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", 

5.336s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.167s loading time
  * 27.629s runtime (conversion to HOG)
  * 0.035s runtime (shuffling)
HOG descriptor size: (880,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 0.620125s prediction time (0.000066 s/image)
  * AUC (weighted): 0.994866888
  * Accuracy: 0.968171725
  * Precision (weighted): 0.968508839
  * Recall (weighted): 0.968171725
  * Confusion Matrix:
[[5806  194]
 [ 107 3350]]

[Classifier statistics (on training data)]:
  * 0.471372s prediction time (0.000079 s/image)
  * AUC (weighted): 0.999907000
  * Accuracy: 0.999666667
  * Precision (weighted): 0.999666667
  * Recall (weighted): 0.999666667
  * Confusion Matrix:
[[2999    1]
 [   1 2999]]

[Falsely detected images]:

####[TEST 9/42]##################################################################
[Current parameter sweep]:
  * Numbe

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", 

2.162s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.071s loading time
  * 23.128s runtime (conversion to HOG)
  * 0.016s runtime (shuffling)
HOG descriptor size: (392,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 0.242561s prediction time (0.000026 s/image)
  * AUC (weighted): 0.987536062
  * Accuracy: 0.948080787
  * Precision (weighted): 0.948856622
  * Recall (weighted): 0.948080787
  * Confusion Matrix:
[[5689  311]
 [ 180 3277]]

[Classifier statistics (on training data)]:
  * 0.164779s prediction time (0.000027 s/image)
  * AUC (weighted): 0.994675333
  * Accuracy: 0.975666667
  * Precision (weighted): 0.975670049
  * Recall (weighted): 0.975666667
  * Confusion Matrix:
[[2931   69]
 [  77 2923]]

[Falsely detected images]:

####[TEST 10/42]##################################################################
[Current parameter sweep]:
  * Numb

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", 

3.763s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.152s loading time
  * 26.840s runtime (conversion to HOG)
  * 0.031s runtime (shuffling)
HOG descriptor size: (616,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 0.417409s prediction time (0.000044 s/image)
  * AUC (weighted): 0.990634365
  * Accuracy: 0.954002326
  * Precision (weighted): 0.954547775
  * Recall (weighted): 0.954002326
  * Confusion Matrix:
[[5729  271]
 [ 164 3293]]

[Classifier statistics (on training data)]:
  * 0.258909s prediction time (0.000043 s/image)
  * AUC (weighted): 0.998696111
  * Accuracy: 0.991500000
  * Precision (weighted): 0.991504424
  * Recall (weighted): 0.991500000
  * Confusion Matrix:
[[2970   30]
 [  21 2979]]

[Falsely detected images]:

####[TEST 11/42]##################################################################
[Current parameter sweep]:
  * Numb

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", 

1.832s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.102s loading time
  * 24.302s runtime (conversion to HOG)
  * 0.022s runtime (shuffling)
HOG descriptor size: (336,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 0.292731s prediction time (0.000031 s/image)
  * AUC (weighted): 0.991269743
  * Accuracy: 0.956751613
  * Precision (weighted): 0.957449578
  * Recall (weighted): 0.956751613
  * Confusion Matrix:
[[5731  269]
 [ 140 3317]]

[Classifier statistics (on training data)]:
  * 0.131394s prediction time (0.000022 s/image)
  * AUC (weighted): 0.995622556
  * Accuracy: 0.977166667
  * Precision (weighted): 0.977181990
  * Recall (weighted): 0.977166667
  * Confusion Matrix:
[[2940   60]
 [  77 2923]]

[Falsely detected images]:

####[TEST 12/42]##################################################################
[Current parameter sweep]:
  * Numb

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", 

2.608s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.115s loading time
  * 22.769s runtime (conversion to HOG)
  * 0.031s runtime (shuffling)
HOG descriptor size: (528,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 0.313324s prediction time (0.000033 s/image)
  * AUC (weighted): 0.993971025
  * Accuracy: 0.962673152
  * Precision (weighted): 0.963410307
  * Recall (weighted): 0.962673152
  * Confusion Matrix:
[[5754  246]
 [ 107 3350]]

[Classifier statistics (on training data)]:
  * 0.175180s prediction time (0.000029 s/image)
  * AUC (weighted): 0.999030111
  * Accuracy: 0.989333333
  * Precision (weighted): 0.989333333
  * Recall (weighted): 0.989333333
  * Confusion Matrix:
[[2968   32]
 [  32 2968]]

[Falsely detected images]:

####[TEST 13/42]##################################################################
[Current parameter sweep]:
  * Numb

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", 

0.646s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.100s loading time
  * 16.638s runtime (conversion to HOG)
  * 0.016s runtime (shuffling)
HOG descriptor size: (140,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 0.079569s prediction time (0.000008 s/image)
  * AUC (weighted): 0.975547344
  * Accuracy: 0.931056360
  * Precision (weighted): 0.932671737
  * Recall (weighted): 0.931056360
  * Confusion Matrix:
[[5575  425]
 [ 227 3230]]

[Classifier statistics (on training data)]:
  * 0.069453s prediction time (0.000012 s/image)
  * AUC (weighted): 0.979534778
  * Accuracy: 0.935666667
  * Precision (weighted): 0.935669765
  * Recall (weighted): 0.935666667
  * Confusion Matrix:
[[2811  189]
 [ 197 2803]]

[Falsely detected images]:

####[TEST 14/42]##################################################################
[Current parameter sweep]:
  * Numb

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", 

0.896s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.141s loading time
  * 17.017s runtime (conversion to HOG)
  * 0.012s runtime (shuffling)
HOG descriptor size: (220,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 0.123173s prediction time (0.000013 s/image)
  * AUC (weighted): 0.986991033
  * Accuracy: 0.950089881
  * Precision (weighted): 0.951318464
  * Recall (weighted): 0.950089881
  * Confusion Matrix:
[[5674  326]
 [ 146 3311]]

[Classifier statistics (on training data)]:
  * 0.085352s prediction time (0.000014 s/image)
  * AUC (weighted): 0.991733111
  * Accuracy: 0.961500000
  * Precision (weighted): 0.961518512
  * Recall (weighted): 0.961500000
  * Confusion Matrix:
[[2875  125]
 [ 106 2894]]

[Falsely detected images]:

####[TEST 15/42]##################################################################
[Current parameter sweep]:
  * Numb

10.839s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.228s loading time
  * 45.168s runtime (conversion to HOG)
  * 0.140s runtime (shuffling)
HOG descriptor size: (3520,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 3.020960s prediction time (0.000319 s/image)
  * AUC (weighted): 0.998419632
  * Accuracy: 0.983292799
  * Precision (weighted): 0.983408338
  * Recall (weighted): 0.983292799
  * Confusion Matrix:
[[5895  105]
 [  53 3404]]

[Classifier statistics (on training data)]:
  * 2.153294s prediction time (0.000359 s/image)
  * AUC (weighted): 1.000000000
  * Accuracy: 1.000000000
  * Precision (weighted): 1.000000000
  * Recall (weighted): 1.000000000
  * Confusion Matrix:
[[3000    0]
 [   0 3000]]

[Falsely detected images]:

####[TEST 21/42]##################################################################
[Current parameter sweep]:
  * Nu

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


12.579s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.117s loading time
  * 37.295s runtime (conversion to HOG)
  * 0.089s runtime (shuffling)
HOG descriptor size: (1764,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 1.577942s prediction time (0.000167 s/image)
  * AUC (weighted): 0.998012053
  * Accuracy: 0.980754996
  * Precision (weighted): 0.980796539
  * Recall (weighted): 0.980754996
  * Confusion Matrix:
[[5897  103]
 [  79 3378]]

[Classifier statistics (on training data)]:
  * 1.112107s prediction time (0.000185 s/image)
  * AUC (weighted): 1.000000000
  * Accuracy: 0.999833333
  * Precision (weighted): 0.999833389
  * Recall (weighted): 0.999833333
  * Confusion Matrix:
[[2999    1]
 [   0 3000]]

[Falsely detected images]:

####[TEST 22/42]##################################################################
[Current parameter sweep]:
  * Nu

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", 

8.072s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.150s loading time
  * 30.250s runtime (conversion to HOG)
  * 0.062s runtime (shuffling)
HOG descriptor size: (1176,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 1.110104s prediction time (0.000117 s/image)
  * AUC (weighted): 0.995841626
  * Accuracy: 0.970075077
  * Precision (weighted): 0.970512156
  * Recall (weighted): 0.970075077
  * Confusion Matrix:
[[5806  194]
 [  89 3368]]

[Classifier statistics (on training data)]:
  * 0.721074s prediction time (0.000120 s/image)
  * AUC (weighted): 0.999702111
  * Accuracy: 0.995166667
  * Precision (weighted): 0.995173324
  * Recall (weighted): 0.995166667
  * Confusion Matrix:
[[2980   20]
 [   9 2991]]

[Falsely detected images]:

####[TEST 24/42]##################################################################
[Current parameter sweep]:
  * Num

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


14.840s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.235s loading time
  * 32.134s runtime (conversion to HOG)
  * 0.071s runtime (shuffling)
HOG descriptor size: (1848,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 1.629481s prediction time (0.000172 s/image)
  * AUC (weighted): 0.996441616
  * Accuracy: 0.972401396
  * Precision (weighted): 0.972644157
  * Recall (weighted): 0.972401396
  * Confusion Matrix:
[[5833  167]
 [  94 3363]]

[Classifier statistics (on training data)]:
  * 1.061194s prediction time (0.000177 s/image)
  * AUC (weighted): 0.999972889
  * Accuracy: 0.999666667
  * Precision (weighted): 0.999666889
  * Recall (weighted): 0.999666667
  * Confusion Matrix:
[[2998    2]
 [   0 3000]]

[Falsely detected images]:

####[TEST 25/42]##################################################################
[Current parameter sweep]:
  * Nu

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", 

5.460s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.149s loading time
  * 29.961s runtime (conversion to HOG)
  * 0.059s runtime (shuffling)
HOG descriptor size: (980,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 0.919405s prediction time (0.000097 s/image)
  * AUC (weighted): 0.998150227
  * Accuracy: 0.981706672
  * Precision (weighted): 0.981884634
  * Recall (weighted): 0.981706672
  * Confusion Matrix:
[[5880  120]
 [  53 3404]]

[Classifier statistics (on training data)]:
  * 0.585304s prediction time (0.000098 s/image)
  * AUC (weighted): 0.999818889
  * Accuracy: 0.995333333
  * Precision (weighted): 0.995333333
  * Recall (weighted): 0.995333333
  * Confusion Matrix:
[[2986   14]
 [  14 2986]]

[Falsely detected images]:

####[TEST 26/42]##################################################################
[Current parameter sweep]:
  * Numb

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


9.674s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.118s loading time
  * 32.154s runtime (conversion to HOG)
  * 0.060s runtime (shuffling)
HOG descriptor size: (1540,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 1.240173s prediction time (0.000131 s/image)
  * AUC (weighted): 0.998243419
  * Accuracy: 0.979909062
  * Precision (weighted): 0.980173141
  * Recall (weighted): 0.979909062
  * Confusion Matrix:
[[5863  137]
 [  53 3404]]

[Classifier statistics (on training data)]:
  * 0.770745s prediction time (0.000128 s/image)
  * AUC (weighted): 0.999997667
  * Accuracy: 0.999500000
  * Precision (weighted): 0.999500056
  * Recall (weighted): 0.999500000
  * Confusion Matrix:
[[2999    1]
 [   2 2998]]

[Falsely detected images]:

####[TEST 27/42]##################################################################
[Current parameter sweep]:
  * Num

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", 

1.108s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.109s loading time
  * 20.118s runtime (conversion to HOG)
  * 0.054s runtime (shuffling)
HOG descriptor size: (336,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 0.354735s prediction time (0.000038 s/image)
  * AUC (weighted): 0.993281313
  * Accuracy: 0.960241091
  * Precision (weighted): 0.961126946
  * Recall (weighted): 0.960241091
  * Confusion Matrix:
[[5735  265]
 [ 111 3346]]

[Classifier statistics (on training data)]:
  * 0.204211s prediction time (0.000034 s/image)
  * AUC (weighted): 0.995794222
  * Accuracy: 0.971166667
  * Precision (weighted): 0.971194362
  * Recall (weighted): 0.971166667
  * Confusion Matrix:
[[2902   98]
 [  75 2925]]

[Falsely detected images]:

####[TEST 28/42]##################################################################
[Current parameter sweep]:
  * Numb

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", 

3.067s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.146s loading time
  * 22.025s runtime (conversion to HOG)
  * 0.050s runtime (shuffling)
HOG descriptor size: (528,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 0.423056s prediction time (0.000045 s/image)
  * AUC (weighted): 0.995037364
  * Accuracy: 0.965951147
  * Precision (weighted): 0.966755749
  * Recall (weighted): 0.965951147
  * Confusion Matrix:
[[5764  236]
 [  86 3371]]

[Classifier statistics (on training data)]:
  * 0.273576s prediction time (0.000046 s/image)
  * AUC (weighted): 0.998061556
  * Accuracy: 0.979166667
  * Precision (weighted): 0.979205482
  * Recall (weighted): 0.979166667
  * Confusion Matrix:
[[2924   76]
 [  49 2951]]

[Falsely detected images]:

####[TEST 29/42]##################################################################
[Current parameter sweep]:
  * Numb

  * 0.315s runtime (shuffling)
HOG descriptor size: (8448,)
28.866s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.141s loading time
  * 37.410s runtime (conversion to HOG)
  * 0.371s runtime (shuffling)
HOG descriptor size: (8448,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 7.860929s prediction time (0.000831 s/image)
  * AUC (weighted): 0.998213383
  * Accuracy: 0.981389447
  * Precision (weighted): 0.981510769
  * Recall (weighted): 0.981389447
  * Confusion Matrix:
[[5886  114]
 [  62 3395]]

[Classifier statistics (on training data)]:
  * 6.591652s prediction time (0.001099 s/image)
  * AUC (weighted): 1.000000000
  * Accuracy: 1.000000000
  * Precision (weighted): 1.000000000
  * Recall (weighted): 1.000000000
  * Confusion Matrix:
[[3000    0]
 [   0 3000]]

[Falsely detected images]:

####[TEST 35/42]########################################

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


24.994s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.125s loading time
  * 29.887s runtime (conversion to HOG)
  * 0.134s runtime (shuffling)
HOG descriptor size: (3920,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 3.614926s prediction time (0.000382 s/image)
  * AUC (weighted): 0.997954392
  * Accuracy: 0.980543513
  * Precision (weighted): 0.980689610
  * Recall (weighted): 0.980543513
  * Confusion Matrix:
[[5879  121]
 [  63 3394]]

[Classifier statistics (on training data)]:
  * 2.346156s prediction time (0.000391 s/image)
  * AUC (weighted): 0.999988000
  * Accuracy: 0.999333333
  * Precision (weighted): 0.999333333
  * Recall (weighted): 0.999333333
  * Confusion Matrix:
[[2998    2]
 [   2 2998]]

[Falsely detected images]:

####[TEST 36/42]##################################################################
[Current parameter sweep]:
  * Nu

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


13.652s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.152s loading time
  * 24.680s runtime (conversion to HOG)
  * 0.098s runtime (shuffling)
HOG descriptor size: (2240,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 2.085975s prediction time (0.000221 s/image)
  * AUC (weighted): 0.996297319
  * Accuracy: 0.970921011
  * Precision (weighted): 0.971405925
  * Recall (weighted): 0.970921011
  * Confusion Matrix:
[[5806  194]
 [  81 3376]]

[Classifier statistics (on training data)]:
  * 1.615371s prediction time (0.000269 s/image)
  * AUC (weighted): 0.999041889
  * Accuracy: 0.989500000
  * Precision (weighted): 0.989504406
  * Recall (weighted): 0.989500000
  * Confusion Matrix:
[[2964   36]
 [  27 2973]]

[Falsely detected images]:

####[TEST 38/42]##################################################################
[Current parameter sweep]:
  * Nu

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


8.709s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.121s loading time
  * 24.970s runtime (conversion to HOG)
  * 0.081s runtime (shuffling)
HOG descriptor size: (1680,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 1.793260s prediction time (0.000190 s/image)
  * AUC (weighted): 0.998428213
  * Accuracy: 0.981072222
  * Precision (weighted): 0.981269846
  * Recall (weighted): 0.981072222
  * Confusion Matrix:
[[5875  125]
 [  54 3403]]

[Classifier statistics (on training data)]:
  * 0.990749s prediction time (0.000165 s/image)
  * AUC (weighted): 0.999464333
  * Accuracy: 0.992333333
  * Precision (weighted): 0.992333552
  * Recall (weighted): 0.992333333
  * Confusion Matrix:
[[2976   24]
 [  22 2978]]

[Falsely detected images]:

####[TEST 40/42]##################################################################
[Current parameter sweep]:
  * Num

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.544s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.102s loading time
  * 14.115s runtime (conversion to HOG)
  * 0.016s runtime (shuffling)
HOG descriptor size: (224,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 0.169135s prediction time (0.000018 s/image)
  * AUC (weighted): 0.991053370
  * Accuracy: 0.953896585
  * Precision (weighted): 0.955419157
  * Recall (weighted): 0.953896585
  * Confusion Matrix:
[[5677  323]
 [ 113 3344]]

[Classifier statistics (on training data)]:
  * 0.095743s prediction time (0.000016 s/image)
  * AUC (weighted): 0.994049889
  * Accuracy: 0.963833333
  * Precision (weighted): 0.963876680
  * Recall (weighted): 0.963833333
  * Confusion Matrix:
[[2877  123]
 [  94 2906]]

[Falsely detected images]:

####[TEST 42/42]##################################################################
[Current parameter sweep]:
  * Numb

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


1.018s runtime (SGD training)
Number of training images loaded: 6000

[Generating test images]:
  * Loading cached unprocessed test images from RAM
    0.085s loading time
  * 18.435s runtime (conversion to HOG)
  * 0.036s runtime (shuffling)
HOG descriptor size: (352,)
Number of testing images loaded: 9457

[Classifier statistics (on test data)]:
  * 0.325624s prediction time (0.000034 s/image)
  * AUC (weighted): 0.992969048
  * Accuracy: 0.959183673
  * Precision (weighted): 0.960327850
  * Recall (weighted): 0.959183673
  * Confusion Matrix:
[[5717  283]
 [ 103 3354]]

[Classifier statistics (on training data)]:
  * 0.203528s prediction time (0.000034 s/image)
  * AUC (weighted): 0.995964333
  * Accuracy: 0.968000000
  * Precision (weighted): 0.968067402
  * Recall (weighted): 0.968000000
  * Confusion Matrix:
[[2886  114]
 [  78 2922]]

[Falsely detected images]:


In [55]:
if RESULTS_FH != None:
    RESULTS_FH.close()
print('{:.3f}s elapsed (entire test)'.format(time.time() - test_start_time))
print('DONE')

3341.587s elapsed (entire test)
DONE
